// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Protocol.proto

/*
Package Protocol is a generated protocol buffer package.

It is generated from these files:
	Protocol.proto

It has these top-level messages:
	RequestMessage
	ResponseMessage
*/
package Protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseMessage_ErrorStatus int32

const (
	// 0-8 是原本的
	ResponseMessage_Succeeded                     ResponseMessage_ErrorStatus = 0
	ResponseMessage_GeneralSocksServerFailure     ResponseMessage_ErrorStatus = 1
	ResponseMessage_ConnectionNotAllowedByRuleset ResponseMessage_ErrorStatus = 2
	ResponseMessage_NetworkUnreachable            ResponseMessage_ErrorStatus = 3
	ResponseMessage_HostUnreachable               ResponseMessage_ErrorStatus = 4
	ResponseMessage_ConnectionRefused             ResponseMessage_ErrorStatus = 5
	ResponseMessage_TtlExpired                    ResponseMessage_ErrorStatus = 6
	ResponseMessage_CommandNotSupported           ResponseMessage_ErrorStatus = 7
	ResponseMessage_AddressTypeNotSupported       ResponseMessage_ErrorStatus = 8
	ResponseMessage_LoginFailed                   ResponseMessage_ErrorStatus = 16
)

var ResponseMessage_ErrorStatus_name = map[int32]string{
	0:  "Succeeded",
	1:  "GeneralSocksServerFailure",
	2:  "ConnectionNotAllowedByRuleset",
	3:  "NetworkUnreachable",
	4:  "HostUnreachable",
	5:  "ConnectionRefused",
	6:  "TtlExpired",
	7:  "CommandNotSupported",
	8:  "AddressTypeNotSupported",
	16: "LoginFailed",
}
var ResponseMessage_ErrorStatus_value = map[string]int32{
	"Succeeded":                     0,
	"GeneralSocksServerFailure":     1,
	"ConnectionNotAllowedByRuleset": 2,
	"NetworkUnreachable":            3,
	"HostUnreachable":               4,
	"ConnectionRefused":             5,
	"TtlExpired":                    6,
	"CommandNotSupported":           7,
	"AddressTypeNotSupported":       8,
	"LoginFailed":                   16,
}

func (x ResponseMessage_ErrorStatus) String() string {
	return proto.EnumName(ResponseMessage_ErrorStatus_name, int32(x))
}
func (ResponseMessage_ErrorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type RequestMessage struct {
	Junk []byte `protobuf:"bytes,17,opt,name=Junk,proto3" json:"Junk,omitempty"`
	// 类型就是参数
	//
	// Types that are valid to be assigned to Command:
	//	*RequestMessage_Hi
	//	*RequestMessage_Connect
	//	*RequestMessage_Bind
	//	*RequestMessage_UdpAssociate
	Command isRequestMessage_Command `protobuf_oneof:"Command"`
}

func (m *RequestMessage) Reset()                    { *m = RequestMessage{} }
func (m *RequestMessage) String() string            { return proto.CompactTextString(m) }
func (*RequestMessage) ProtoMessage()               {}
func (*RequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isRequestMessage_Command interface {
	isRequestMessage_Command()
}

type RequestMessage_Hi struct {
	Hi *RequestMessage_Greet `protobuf:"bytes,1,opt,name=Hi,oneof"`
}
type RequestMessage_Connect struct {
	Connect string `protobuf:"bytes,5,opt,name=Connect,oneof"`
}
type RequestMessage_Bind struct {
	Bind string `protobuf:"bytes,22,opt,name=Bind,oneof"`
}
type RequestMessage_UdpAssociate struct {
	UdpAssociate string `protobuf:"bytes,23,opt,name=UdpAssociate,oneof"`
}

func (*RequestMessage_Hi) isRequestMessage_Command()           {}
func (*RequestMessage_Connect) isRequestMessage_Command()      {}
func (*RequestMessage_Bind) isRequestMessage_Command()         {}
func (*RequestMessage_UdpAssociate) isRequestMessage_Command() {}

func (m *RequestMessage) GetCommand() isRequestMessage_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *RequestMessage) GetJunk() []byte {
	if m != nil {
		return m.Junk
	}
	return nil
}

func (m *RequestMessage) GetHi() *RequestMessage_Greet {
	if x, ok := m.GetCommand().(*RequestMessage_Hi); ok {
		return x.Hi
	}
	return nil
}

func (m *RequestMessage) GetConnect() string {
	if x, ok := m.GetCommand().(*RequestMessage_Connect); ok {
		return x.Connect
	}
	return ""
}

func (m *RequestMessage) GetBind() string {
	if x, ok := m.GetCommand().(*RequestMessage_Bind); ok {
		return x.Bind
	}
	return ""
}

func (m *RequestMessage) GetUdpAssociate() string {
	if x, ok := m.GetCommand().(*RequestMessage_UdpAssociate); ok {
		return x.UdpAssociate
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RequestMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RequestMessage_OneofMarshaler, _RequestMessage_OneofUnmarshaler, _RequestMessage_OneofSizer, []interface{}{
		(*RequestMessage_Hi)(nil),
		(*RequestMessage_Connect)(nil),
		(*RequestMessage_Bind)(nil),
		(*RequestMessage_UdpAssociate)(nil),
	}
}

func _RequestMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RequestMessage)
	// Command
	switch x := m.Command.(type) {
	case *RequestMessage_Hi:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Hi); err != nil {
			return err
		}
	case *RequestMessage_Connect:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Connect)
	case *RequestMessage_Bind:
		b.EncodeVarint(22<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Bind)
	case *RequestMessage_UdpAssociate:
		b.EncodeVarint(23<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.UdpAssociate)
	case nil:
	default:
		return fmt.Errorf("RequestMessage.Command has unexpected type %T", x)
	}
	return nil
}

func _RequestMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RequestMessage)
	switch tag {
	case 1: // Command.Hi
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestMessage_Greet)
		err := b.DecodeMessage(msg)
		m.Command = &RequestMessage_Hi{msg}
		return true, err
	case 5: // Command.Connect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Command = &RequestMessage_Connect{x}
		return true, err
	case 22: // Command.Bind
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Command = &RequestMessage_Bind{x}
		return true, err
	case 23: // Command.UdpAssociate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Command = &RequestMessage_UdpAssociate{x}
		return true, err
	default:
		return false, nil
	}
}

func _RequestMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RequestMessage)
	// Command
	switch x := m.Command.(type) {
	case *RequestMessage_Hi:
		s := proto.Size(x.Hi)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RequestMessage_Connect:
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Connect)))
		n += len(x.Connect)
	case *RequestMessage_Bind:
		n += proto.SizeVarint(22<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Bind)))
		n += len(x.Bind)
	case *RequestMessage_UdpAssociate:
		n += proto.SizeVarint(23<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.UdpAssociate)))
		n += len(x.UdpAssociate)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RequestMessage_Greet struct {
	RandomNumber uint64 `protobuf:"fixed64,1,opt,name=RandomNumber" json:"RandomNumber,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=UserName" json:"UserName,omitempty"`
}

func (m *RequestMessage_Greet) Reset()                    { *m = RequestMessage_Greet{} }
func (m *RequestMessage_Greet) String() string            { return proto.CompactTextString(m) }
func (*RequestMessage_Greet) ProtoMessage()               {}
func (*RequestMessage_Greet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *RequestMessage_Greet) GetRandomNumber() uint64 {
	if m != nil {
		return m.RandomNumber
	}
	return 0
}

func (m *RequestMessage_Greet) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type ResponseMessage struct {
	Status ResponseMessage_ErrorStatus `protobuf:"varint,1,opt,name=Status,enum=Protocol.ResponseMessage_ErrorStatus" json:"Status,omitempty"`
	Junk   []byte                      `protobuf:"bytes,17,opt,name=Junk,proto3" json:"Junk,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*ResponseMessage_RandomNumber
	//	*ResponseMessage_Bind
	Value isResponseMessage_Value `protobuf_oneof:"Value"`
}

func (m *ResponseMessage) Reset()                    { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()               {}
func (*ResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isResponseMessage_Value interface {
	isResponseMessage_Value()
}

type ResponseMessage_RandomNumber struct {
	RandomNumber uint64 `protobuf:"fixed64,2,opt,name=RandomNumber,oneof"`
}
type ResponseMessage_Bind struct {
	Bind string `protobuf:"bytes,20,opt,name=Bind,oneof"`
}

func (*ResponseMessage_RandomNumber) isResponseMessage_Value() {}
func (*ResponseMessage_Bind) isResponseMessage_Value()         {}

func (m *ResponseMessage) GetValue() isResponseMessage_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ResponseMessage) GetStatus() ResponseMessage_ErrorStatus {
	if m != nil {
		return m.Status
	}
	return ResponseMessage_Succeeded
}

func (m *ResponseMessage) GetJunk() []byte {
	if m != nil {
		return m.Junk
	}
	return nil
}

func (m *ResponseMessage) GetRandomNumber() uint64 {
	if x, ok := m.GetValue().(*ResponseMessage_RandomNumber); ok {
		return x.RandomNumber
	}
	return 0
}

func (m *ResponseMessage) GetBind() string {
	if x, ok := m.GetValue().(*ResponseMessage_Bind); ok {
		return x.Bind
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ResponseMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ResponseMessage_OneofMarshaler, _ResponseMessage_OneofUnmarshaler, _ResponseMessage_OneofSizer, []interface{}{
		(*ResponseMessage_RandomNumber)(nil),
		(*ResponseMessage_Bind)(nil),
	}
}

func _ResponseMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ResponseMessage)
	// Value
	switch x := m.Value.(type) {
	case *ResponseMessage_RandomNumber:
		b.EncodeVarint(2<<3 | proto.WireFixed64)
		b.EncodeFixed64(uint64(x.RandomNumber))
	case *ResponseMessage_Bind:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Bind)
	case nil:
	default:
		return fmt.Errorf("ResponseMessage.Value has unexpected type %T", x)
	}
	return nil
}

func _ResponseMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ResponseMessage)
	switch tag {
	case 2: // Value.RandomNumber
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &ResponseMessage_RandomNumber{x}
		return true, err
	case 20: // Value.Bind
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &ResponseMessage_Bind{x}
		return true, err
	default:
		return false, nil
	}
}

func _ResponseMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ResponseMessage)
	// Value
	switch x := m.Value.(type) {
	case *ResponseMessage_RandomNumber:
		n += proto.SizeVarint(2<<3 | proto.WireFixed64)
		n += 8
	case *ResponseMessage_Bind:
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Bind)))
		n += len(x.Bind)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*RequestMessage)(nil), "Protocol.RequestMessage")
	proto.RegisterType((*RequestMessage_Greet)(nil), "Protocol.RequestMessage.Greet")
	proto.RegisterType((*ResponseMessage)(nil), "Protocol.ResponseMessage")
	proto.RegisterEnum("Protocol.ResponseMessage_ErrorStatus", ResponseMessage_ErrorStatus_name, ResponseMessage_ErrorStatus_value)
}

func init() { proto.RegisterFile("Protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xd3, 0x7c, 0x4e, 0x42, 0xe2, 0x4e, 0x4b, 0x63, 0x82, 0x8a, 0x42, 0x54, 0xa4, 0x9c,
	0x22, 0x54, 0xce, 0x1c, 0x12, 0x54, 0x12, 0x21, 0x88, 0xd0, 0xba, 0xe1, 0xbe, 0xf1, 0x0e, 0xc5,
	0x8a, 0xbd, 0x6b, 0xf6, 0x83, 0xd2, 0x2b, 0xff, 0x85, 0x1f, 0xc9, 0x0d, 0xd9, 0x38, 0x25, 0x46,
	0xdc, 0x76, 0xde, 0x9b, 0x79, 0xf3, 0xe6, 0x69, 0xa1, 0xff, 0x51, 0x2b, 0xab, 0x22, 0x95, 0xcc,
	0xb2, 0xfc, 0x81, 0xed, 0x7d, 0x3d, 0xf9, 0x51, 0x83, 0x3e, 0xa3, 0xaf, 0x8e, 0x8c, 0xfd, 0x40,
	0xc6, 0xf0, 0x5b, 0x42, 0x84, 0xfa, 0x3b, 0x27, 0x77, 0xc1, 0xc9, 0xd8, 0x9b, 0xf6, 0x58, 0xf1,
	0xc6, 0x97, 0x50, 0x5b, 0xc5, 0x81, 0x37, 0xf6, 0xa6, 0xdd, 0xab, 0x67, 0xb3, 0x07, 0xb5, 0xea,
	0xe4, 0x6c, 0xa9, 0x89, 0xec, 0xea, 0x88, 0xd5, 0x56, 0x31, 0x8e, 0xa0, 0xf5, 0x46, 0x49, 0x49,
	0x91, 0x0d, 0x1a, 0x63, 0x6f, 0xda, 0x59, 0x1d, 0xb1, 0x3d, 0x80, 0x67, 0x50, 0x5f, 0xc4, 0x52,
	0x04, 0xe7, 0x25, 0x51, 0x54, 0x78, 0x09, 0xbd, 0x8d, 0xc8, 0xe6, 0xc6, 0xa8, 0x28, 0xe6, 0x96,
	0x82, 0x61, 0xc9, 0x56, 0xd0, 0xd1, 0x12, 0x1a, 0xc5, 0x1a, 0x9c, 0x40, 0x8f, 0x71, 0x29, 0x54,
	0xba, 0x76, 0xe9, 0x96, 0x74, 0x61, 0xae, 0xc9, 0x2a, 0x18, 0x8e, 0xa0, 0xbd, 0x31, 0xa4, 0xd7,
	0x3c, 0xa5, 0xa0, 0x96, 0xcb, 0xb1, 0x87, 0x7a, 0xd1, 0xc9, 0x0d, 0xa6, 0x29, 0x97, 0x62, 0xf2,
	0xf3, 0x18, 0x06, 0x8c, 0x4c, 0xa6, 0xa4, 0xa1, 0x7d, 0x0a, 0xaf, 0xa1, 0x19, 0x5a, 0x6e, 0x9d,
	0x29, 0x84, 0xfb, 0x57, 0x2f, 0x0e, 0xaf, 0xae, 0xb4, 0xce, 0xae, 0xb5, 0x56, 0xfa, 0x4f, 0x33,
	0x2b, 0x87, 0xfe, 0x1b, 0xe2, 0xe5, 0x3f, 0x8e, 0x73, 0x47, 0xcd, 0xfc, 0xc0, 0x8a, 0xe7, 0x7d,
	0x38, 0x67, 0x87, 0xe1, 0x4c, 0x7e, 0x79, 0xd0, 0x3d, 0xd8, 0x83, 0x8f, 0xa0, 0x13, 0xba, 0x28,
	0x22, 0x12, 0x24, 0xfc, 0x23, 0xbc, 0x80, 0x27, 0x4b, 0x92, 0xa4, 0x79, 0x12, 0xaa, 0x68, 0x67,
	0x42, 0xd2, 0xdf, 0x48, 0xbf, 0xe5, 0x71, 0xe2, 0x34, 0xf9, 0x1e, 0x3e, 0x87, 0x8b, 0x32, 0xfb,
	0x58, 0xc9, 0xb5, 0xb2, 0xf3, 0x24, 0x51, 0x77, 0x24, 0x16, 0xf7, 0xcc, 0x25, 0x64, 0xc8, 0xfa,
	0x35, 0x3c, 0x07, 0x5c, 0x93, 0xbd, 0x53, 0x7a, 0xb7, 0x91, 0x9a, 0x78, 0xf4, 0x85, 0x6f, 0x13,
	0xf2, 0x8f, 0xf1, 0x14, 0x06, 0x2b, 0x65, 0xec, 0x21, 0x58, 0xc7, 0xc7, 0x70, 0xf2, 0x57, 0x8f,
	0xd1, 0x67, 0x67, 0x48, 0xf8, 0x0d, 0xec, 0x03, 0xdc, 0xd8, 0xe4, 0xfa, 0x7b, 0x16, 0x6b, 0x12,
	0x7e, 0x13, 0x87, 0x70, 0x5a, 0x46, 0xbc, 0x56, 0x36, 0x74, 0x59, 0xa6, 0xb4, 0x25, 0xe1, 0xb7,
	0xf0, 0x29, 0x0c, 0xe7, 0x42, 0x68, 0x32, 0xe6, 0xe6, 0x3e, 0xa3, 0x0a, 0xd9, 0xc6, 0x01, 0x74,
	0xdf, 0xab, 0xdb, 0x58, 0xe6, 0xf6, 0x49, 0xf8, 0xfe, 0xa2, 0x05, 0x8d, 0x4f, 0x3c, 0x71, 0xb4,
	0x6d, 0x16, 0xbf, 0xf7, 0xd5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x07, 0x68, 0x3a, 0xcf,
	0x02, 0x00, 0x00,
}
